version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: redis-standalone
    ports:
      - "6380:6379"
    environment:
      - REDIS_PASSWORD=changeit
      - REDIS_USERNAME=username
    command: ["redis-server", "--requirepass", "changeit", "--user", "username"]
    volumes:
      - redis_data:/data
    networks:
      - redis_network

volumes:
  redis_data:
    driver: local

networks:
  redis_network:
    driver: bridge
